id: PF7ABA5CE
initial_creation_type: ocr
source_metadata:
  volumes:
    7cb7d0cf16a843ea91d69a630e05768f:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: བཤེས་པའི་སྤྲིང་ཡིག།
      total_pages: 1144
      volume_number: 96
